### PR TITLE
chore: Bump @material-ui dependencies

### PR DESCRIPTION
**Pull request by diyorbek**

### CODE REVIEW

**Comment by diyorbek** [comment]
@doniyor2109 can you help with the failing builds?

**Comment by doniyor2109** [comment]
@diyorbek Is this branch comes from your fork? If so try it does not pass GITHUB access token. Try to create PR from original repo.
https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by diyorbek** [comment]
@doniyor2109 I don't have any privileges in this repo. maybe you could me access?

**Comment by doniyor2109** [comment]
@diyorbek @superdispatch/web has a `Maintain` permission to this repo. Are you in this team?

**Comment by diyorbek** [comment]
@doniyor2109 I am but i couldn't push my branch from this repo. That's why I am send it from fork

**Pull request closed without merging**
